/// Farm profile model for the My Farm feature.
/// Maps to the `farm_profiles` table in Supabase.
class FarmProfile {
  final String id;
  final String userId;
  final String province;
  final String? nearestCity;
  final int? totalAcres;
  final int engagementLevel;
  final DateTime? createdAt;
  final DateTime? updatedAt;

  /// Valid prairie provinces for farm profiles.
  static const validProvinces = ['SK', 'AB', 'MB'];

  FarmProfile({
    required this.id,
    required this.userId,
    required this.province,
    this.nearestCity,
    this.totalAcres,
    this.engagementLevel = 1,
    this.createdAt,
    this.updatedAt,
  });

  factory FarmProfile.fromMap(Map<String, dynamic> map) {
    return FarmProfile(
      id: map['id'] as String,
      userId: map['user_id'] as String,
      province: map['province'] as String,
      nearestCity: map['nearest_city'] as String?,
      totalAcres: map['total_acres'] as int?,
      engagementLevel: (map['engagement_level'] as int?) ?? 1,
      createdAt: map['created_at'] != null
          ? DateTime.parse(map['created_at'] as String)
          : null,
      updatedAt: map['updated_at'] != null
          ? DateTime.parse(map['updated_at'] as String)
          : null,
    );
  }

  /// Returns a map suitable for inserting into the `farm_profiles` table.
  /// Excludes `id`, `created_at`, and `updated_at` (auto-generated by DB).
  Map<String, dynamic> toInsertMap() {
    return {
      'user_id': userId,
      'province': province,
      if (nearestCity != null) 'nearest_city': nearestCity,
      if (totalAcres != null) 'total_acres': totalAcres,
      'engagement_level': engagementLevel,
    };
  }

  FarmProfile copyWith({
    String? province,
    String? nearestCity,
    int? totalAcres,
    int? engagementLevel,
  }) {
    return FarmProfile(
      id: id,
      userId: userId,
      province: province ?? this.province,
      nearestCity: nearestCity ?? this.nearestCity,
      totalAcres: totalAcres ?? this.totalAcres,
      engagementLevel: engagementLevel ?? this.engagementLevel,
      createdAt: createdAt,
      updatedAt: updatedAt,
    );
  }
}
