// File generated by FlutterFire CLI / Agent.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQHR6C5WHB_AupijGkAeYyIhL_AQlZDfQ',
    appId: '1:863523401515:web:f4a7141599f528ffc31f6e',
    messagingSenderId: '863523401515',
    projectId: 'agnonymous-beta-kyle-2005b',
    authDomain: 'agnonymous-beta-kyle-2005b.firebaseapp.com',
    storageBucket: 'agnonymous-beta-kyle-2005b.firebasestorage.app',
    measurementId: 'G-DYYL6SKGXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLnP27KypE6d1M1f_BrjzYS2LuryPwNj4',
    appId: '1:863523401515:android:5b7873b89b5e25d2c31f6e',
    messagingSenderId: '863523401515',
    projectId: 'agnonymous-beta-kyle-2005b',
    storageBucket: 'agnonymous-beta-kyle-2005b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvOubH_iwvaLr-ngmIIX47VmUJ_7hwU0o',
    appId: '1:863523401515:ios:b14bd4ddf0846f86c31f6e',
    messagingSenderId: '863523401515',
    projectId: 'agnonymous-beta-kyle-2005b',
    storageBucket: 'agnonymous-beta-kyle-2005b.firebasestorage.app',
    iosBundleId: 'com.example.agnonymousBeta',
  );
}
